/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */

plugins {
    application
    kotlin("plugin.serialization") version "1.4.0"
    kotlin("jvm") version "1.4.0"
}