/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */

plugins {
    application
    kotlin("plugin.serialization") version "1.4.0"
    kotlin("jvm") version "1.4.0"
    id("com.google.cloud.tools.appengine") version "2.4.1"
}

repositories {
    mavenCentral()
}

configure<com.google.cloud.tools.gradle.appengine.appyaml.AppEngineAppYamlExtension> {
    val project = System.getenv("GCP_PROJECT")

    deploy {
        projectId = project
    }
}


kotlin {
    sourceSets {
       main {
       }
        test {
            dependencies {
                implementation(kotlin("test-junit"))
                implementation("org.junit.jupiter:junit-jupiter:5.4.2")
                implementation("org.assertj:assertj-core:3.15.0")
                implementation("io.mockk:mockk:1.10.2")
            }
        }
    }
}